# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: identity-api-client 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "identity-api-client".freeze
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Nathan Woodhull".freeze]
  s.date = "2023-12-12"
  s.description = "Provides a simple ruby binding to 38dgs identity API".freeze
  s.email = "nathan@controlshiftlabs.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-gemset",
    ".ruby-version",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "identity-api-client.gemspec",
    "lib/identity-api-client.rb",
    "lib/identity-api-client/actions.rb",
    "lib/identity-api-client/base.rb",
    "lib/identity-api-client/client.rb",
    "lib/identity-api-client/employment_data.rb",
    "lib/identity-api-client/industries.rb",
    "lib/identity-api-client/interests.rb",
    "lib/identity-api-client/list.rb",
    "lib/identity-api-client/lists.rb",
    "lib/identity-api-client/mailing.rb",
    "lib/identity-api-client/mailing_api_base.rb",
    "lib/identity-api-client/mailings.rb",
    "lib/identity-api-client/member.rb",
    "lib/identity-api-client/professions.rb",
    "lib/identity-api-client/search.rb",
    "lib/identity-api-client/searches.rb",
    "lib/identity-api-client/workplaces.rb",
    "spec/client_spec.rb",
    "spec/fixtures/details.json",
    "spec/fixtures/details_with_consents.json",
    "spec/fixtures/get_mailing_response.json",
    "spec/fixtures/new_mailing_request.json",
    "spec/fixtures/new_mailing_response.json",
    "spec/mailings_spec.rb",
    "spec/member_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/controlshift/identity-api-client".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.2.22".freeze
  s.summary = "API Client for 38 Degree's Identity API".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<vertebrae>.freeze, ["= 0.8.0"])
    s.add_development_dependency(%q<pry>.freeze, [">= 0"])
    s.add_development_dependency(%q<pry-byebug>.freeze, [">= 0"])
    s.add_development_dependency(%q<webmock>.freeze, [">= 0"])
    s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
    s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
  else
    s.add_dependency(%q<vertebrae>.freeze, ["= 0.8.0"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
    s.add_dependency(%q<pry-byebug>.freeze, [">= 0"])
    s.add_dependency(%q<webmock>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

